export default function Site() {
    return (<div className='min-h-screen bg-gradient-to-b from-stone-50 via-white to-stone-100 text-zinc-800 font-sans'>
        <header className='max-w-6xl mx-auto px-6 py-8 flex justify-between items-center backdrop-blur sticky top-0 bg-white/70 z-50'><div><h1 className='text-2xl font-semibold'>Ярослав Дорошенко</h1><p className='text-sm text-zinc-500'>Екзистенційний психолог</p></div><div className='space-x-3'><button className='px-4 py-2 rounded-2xl bg-zinc-900 text-white'>Записатись</button><button className='px-4 py-2 rounded-2xl border'>Telegram @yourhandle</button></div></header>
        <main>
            <section className='max-w-6xl mx-auto px-6 pt-4'><div className='text-sm text-zinc-500'>Онлайн консультації • UA / EN • Конфіденційно • Відповідь протягом 24 годин</div></section>
            <section className='max-w-6xl mx-auto px-6 py-20 grid md:grid-cols-2 gap-10 items-center'><div><h2 className='text-5xl md:text-6xl font-semibold leading-tight tracking-tight'>Допомагаю пройти кризи, повернути сенс і знайти себе.</h2><p className='mt-6 text-lg text-zinc-600'>Індивідуальна терапія, робота з парами, підтримка підлітків та психоделічна інтеграція.</p><div className='mt-8 space-x-3'><button className='px-5 py-3 rounded-2xl bg-zinc-900 text-white shadow-lg hover:-translate-y-0.5 transition'>Записатись</button><button className='px-5 py-3 rounded-2xl border'>Безкоштовний перший контакт</button></div><p className='mt-4 text-sm text-zinc-500'>15 хвилин знайомства, щоб зрозуміти ваш запит і формат роботи.</p></div><div className='rounded-[2rem] bg-gradient-to-br from-stone-200 via-white to-stone-100 h-96 shadow-2xl flex items-center justify-center text-zinc-500 border'>Premium Calm Presence</div></section>
            <section className='bg-white/80 backdrop-blur py-16'><div className='max-w-6xl mx-auto px-6'><h3 className='text-3xl font-semibold mb-8'>Чим можу допомогти</h3><div className='grid md:grid-cols-2 gap-6'>{['Тривога, втрата сенсу, кризи', 'Стосунки, конфлікти, дистанція', 'Пошук себе у підлітковому віці', 'Інтеграція глибоких переживань'].map((t, i) => <div key={i} className='p-6 rounded-3xl border bg-stone-50'>{t}</div>)}</div></div></section>
            <section className='py-16'><div className='max-w-6xl mx-auto px-6'><h3 className='text-3xl font-semibold mb-2'>Послуги</h3><p className='text-zinc-600 mb-8'>Формат роботи підбирається під ваш запит та життєву ситуацію.</p><div className='grid md:grid-cols-2 gap-6'>{[['Індивідуальна терапія', 'Глибока робота з внутрішніми труднощами.'], ['Консультації для пар', 'Відновлення діалогу та близькості.'], ['Консультації підлітків', 'Підтримка в період становлення.'], ['Психоделічна інтеграція', 'Осмислення досвіду та зміни в житті.']].map((item, i) => <div key={i} className='p-6 rounded-3xl bg-white shadow-sm'><h4 className='font-semibold text-xl'>{item[0]}</h4><p className='mt-2 text-zinc-600'>{item[1]}</p></div>)}</div></div></section>
            <section className='py-16 bg-white'><div className='max-w-6xl mx-auto px-6'><h3 className='text-3xl font-semibold mb-2'>Чому мені довіряють</h3><p className='text-zinc-600 mb-8'>Повага до вашої історії, конфіденційність та орієнтація на результат.</p><div className='grid md:grid-cols-3 gap-6'><div className='p-6 rounded-3xl border'>Безпечний простір без осуду</div><div className='p-6 rounded-3xl border'>Глибина замість шаблонних порад</div><div className='p-6 rounded-3xl border'>Орієнтація на реальні зміни</div></div></div></section><section className='bg-gradient-to-r from-zinc-900 to-zinc-800 text-white py-20'><div className='max-w-4xl mx-auto px-6 text-center'><h3 className='text-4xl font-semibold'>Почнімо зміни вже сьогодні</h3><p className='mt-4 text-zinc-300'>Конфіденційний простір для глибокої розмови. Онлайн консультації UA / EN.</p><div className='mt-8 space-x-3'><button className='px-5 py-3 rounded-2xl bg-white text-zinc-900'>Записатись</button><button className='px-5 py-3 rounded-2xl border border-white'>Telegram @yourhandle</button></div></div></section>
        </main>
        <section className='py-16'><div className='max-w-6xl mx-auto px-6'><h3 className='text-3xl font-semibold mb-2'>Блог</h3><p className='text-zinc-600 mb-8'>Матеріали, які допомагають зрозуміти себе вже зараз.</p><div className='grid md:grid-cols-3 gap-6'><div className='p-6 rounded-3xl bg-white shadow-sm'>Як знайти сенс у кризі</div><div className='p-6 rounded-3xl bg-white shadow-sm'>Чому тривога говорить важливе</div><div className='p-6 rounded-3xl bg-white shadow-sm'>Після глибокого досвіду: що далі?</div></div></div></section><section className='py-16 bg-stone-50'><div className='max-w-4xl mx-auto px-6'><h3 className='text-3xl font-semibold mb-6 text-center'>Залишити заявку</h3><div className='grid gap-4'><input className='p-4 rounded-2xl border' placeholder='Ваше імʼя' /><input className='p-4 rounded-2xl border' placeholder='Telegram або Email' /><textarea className='p-4 rounded-2xl border min-h-32' placeholder='Коротко опишіть запит'></textarea><button className='px-5 py-3 rounded-2xl bg-zinc-900 text-white'>Надіслати заявку</button></div></div></section><footer className='max-w-6xl mx-auto px-6 py-10 text-sm text-zinc-500'>© 2026 Yaroslav Doroshenko • Online Worldwide • Confidential</footer>

    </div>)
}
